const ROUTES = {
    HOME_PAGE: 'HOME_PAGE',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    REGISTER: 'REGISTER',
    ADD_BOOK: 'ADD_BOOK',
    ADD_TYPE: 'ADD_TYPE',
    ADD_AUTHOR: 'ADD_AUTHOR',
    NEW_USER_BOOK: 'NEW_USER_BOOK'
}

export default ROUTES;